config/routes.rb
Jangle::Application.routes.draw do

  namespace :jangle, :path => Jangle.config.admin_route_prefix, :except => :show do
    get '/' => redirect(Jangle.config.admin_route_redirect)
    resources :pages
    resources :sites
    resources :layouts
    resources :widgets
    resources :assets
  end

  get File.join(Jangle.config.cms_css_path, ':slug(.:format)') => 'jangle/rendering#css', :as => 'cms_css'
  get File.join(Jangle.config.cms_js_path,  ':slug(.:format)') => 'jangle/rendering#js',  :as => 'cms_js'
  match '/'     => 'jangle/rendering#show'
  match '*path' => 'jangle/rendering#show'

end

app/models/jangle/asset.rb
class Jangle::Asset
  include Mongoid::Document
  include Mongoid::Timestamps

  # -- Fields ---------------------------------------------------------------
  field :name,         :type => String
  field :content_type, :type => String
  field :width,        :type => Integer
  field :height,       :type => Integer
  field :size,         :type => Integer
  field :position,     :type => Integer, :default => 0
  mount_uploader :source, Jangle::AssetUploader

  # -- Relationships --------------------------------------------------------
  referenced_in :site,
    :class_name => 'Jangle::Site',
    :inverse_of => :assets

  # -- Validations ----------------------------------------------------------
  validates_presence_of :name, :source

  # -- Instance Methods -----------------------------------------------------
  %w{image stylesheet javascript pdf media}.each do |type|
    define_method("#{type}?") do
      self.content_type.to_s == type
    end
  end

  def extname
    return nil unless self.source?
    File.extname(self.source_filename).gsub(/^\./, '')
  end

end

app/models/jangle/block.rb
class Jangle::Block
  include Jangle::Mongoid::Document

  # -- Fields ---------------------------------------------------------------
  field :label,   :type => String
  field :content, :type => String

  embedded_in :container, :polymorphic => true

  # -- Validations ----------------------------------------------------------
  #validates :label,
  #  :presence   => true,
  #  :uniqueness => { :scope => :jangle_page_id }
end

app/models/jangle/extensions/parse.rb
module Models
  module Jangle
    module Extensions
      module Parse
        extend ActiveSupport::Concern

        module InstanceMethods
          def template(reload = false)
            @template = nil if reload
            @template ||= ::Liquid::Template.parse(self.content)
          end
        end
      end
    end
  end
end

app/models/jangle/extensions/redirect.rb
module Models
  module Jangle
    module Extensions
      module Redirect

        extend ActiveSupport::Concern

        included do

          field :redirect, :type => Boolean, :default => false

          field :redirect_url, :type => String

          validates_presence_of :redirect_url, :if => :redirect

          validates_format_of   :redirect_url, :with => ::Jangle::Regexps::URL, :allow_blank => true

        end

      end
    end
  end
end

app/models/jangle/extensions/render.rb
module Models
  module Jangle
    module Extensions
      module Render
        extend ActiveSupport::Concern

        module InstanceMethods
          def render(context)
            if self.respond_to?(:layout)
              layout.render('content_for_layout' => self.template.render(context))
            else
              self.template.render(context)
            end
          end
        end
      end
    end
  end
end

app/models/jangle/layout.rb
class Jangle::Layout
  include Jangle::Mongoid::Document
  include Mongoid::Tree

  include Models::Jangle::Extensions::Parse
  include Models::Jangle::Extensions::Render

  # -- Fields ---------------------------------------------------------------
  field :label,      :type => String
  field :slug,       :type => String
  field :app_layout, :type => String
  field :content,    :type => String
  field :css,        :type => String
  field :js,         :type => String
  field :position,   :type => Integer, :default => 0

  # -- Relationships --------------------------------------------------------
  referenced_in :site,
    :class_name => 'Jangle::Site',
    :inverse_of => :layouts
  references_many :pages,
    :class_name => 'Jangle::Page',
    :inverse_of => :layout,
    :dependent => :nullify
  references_many :widgets,
    :class_name => 'Jangle::Widget',
    :inverse_of => :layout,
    :dependent => :nullify

  # -- Validations ----------------------------------------------------------
  validates :site_id,
    :presence   => true
  validates :label,
    :presence   => true
  validates :content,
    :presence   => true

  # -- Class Methods --------------------------------------------------------
  # Tree-like structure for layouts
  def self.options_for_select(jangle_site, jangle_layout = nil, current_layout = nil, depth = 0, spacer = '. . ')
    out = []
    [current_layout || jangle_site.layouts.roots].flatten.each do |layout|
      next if jangle_layout == layout
      out << [ "#{spacer*depth}#{layout.label}", layout.id ]
      layout.children.each do |child|
        out += options_for_select(jangle_site, jangle_layout, child, depth + 1, spacer)
      end
    end
    return out.compact
  end

  # List of available application layouts
  def self.app_layouts_for_select(default = nil)
    Dir.glob(File.expand_path('app/views/layouts/*.html.*', Rails.root)).collect do |filename|
      match = filename.match(/\w*.html.\w*$/)
      app_layout = match && match[0]
      app_layout.to_s[0...1] == '_' ? nil : app_layout
    end.compact.unshift([default, nil])
  end
end

app/models/jangle/page.rb
class Jangle::Page
  include Jangle::Mongoid::Document
  include Mongoid::Tree

  include Models::Jangle::Extensions::Parse
  include Models::Jangle::Extensions::Render
  include Models::Jangle::Extensions::Redirect

  # -- Fields ---------------------------------------------------------------
  field :label,     :type => String
  field :slug,      :type => String
  field :fullpath,  :type => String
  field :content,   :type => String
  field :position,  :type => Integer, :default => 0
  field :published, :type => Boolean, :default => false

  # -- Relationships --------------------------------------------------------
  referenced_in :site,
    :class_name => 'Jangle::Site',
    :inverse_of => :pages
  referenced_in :layout,
    :class_name => 'Jangle::Layout',
    :inverse_of => :pages
  embeds_many :blocks,
    :class_name => 'Jangle::Block',
    :as         => :container
  accepts_nested_attributes_for :blocks

  # -- Callbacks ------------------------------------------------------------
  before_save { |p| p.fullpath = p.fullpath(true) }

  # -- Named Scopes ---------------------------------------------------------
  scope :root_index, :where => { :slug => 'index' }
  scope :not_found,  :where => { :slug => '404' }
  scope :published,  :where => { :published => true }

  # -- Validations ----------------------------------------------------------
  validates :site_id, 
    :presence => true
  validates :label,
    :presence => true
  validates :layout,
    :presence => true

  # -- Class Methods --------------------------------------------------------
  # Tree-like structure for pages
  def self.options_for_select(jangle_site, jangle_page = nil, current_page = nil, depth = 0, spacer = '. . ')
    return [] if self.count == 0
    out = []
    [current_page || jangle_site.pages.roots].flatten.each do |page|
      next if jangle_page == page
      out << [ "#{spacer*depth}#{page.slug} (#{page.label})", page.id ]
      page.children.each do |child|
        out += options_for_select(jangle_site, jangle_page, child, depth + 1, spacer)
      end
    end
    return out.compact
  end

  # -- Instance Methods -----------------------------------------------------
  def index?
    self.slug == 'index'
  end

  def not_found?
    self.slug == '404'
  end

  def index_or_not_found?
    self.index? || self.not_found?
  end

  def fullpath(force = false)
    if read_attribute(:fullpath).present? && !force
      return read_attribute(:fullpath)
    end

    if self.index_or_not_found?
      self.slug
    else
      slugs = self.ancestors_and_self.map(&:slug)
      File.join slugs
    end
  end

  # Full url for a page
  def url(force = false)
    "http://#{self.site.hostname}/#{self.fullpath(force)}"
  end
end

app/models/jangle/site.rb
class Jangle::Site
  include Jangle::Mongoid::Document

  # -- Fields ---------------------------------------------------------------
  field :label,    :type => String, :default => 'Default Site'
  field :hostname, :type => String

  # -- Relationships --------------------------------------------------------
  references_many :layouts,
    :class_name => 'Jangle::Layout',
    :inverse_of => :site,
    :dependent => :destroy
  references_many :pages,
    :class_name => 'Jangle::Page',
    :inverse_of => :site,
    :dependent => :destroy
  references_many :widgets,
    :class_name => 'Jangle::Widget',
    :inverse_of => :site,
    :dependent => :destroy
  references_many :assets,
    :class_name => 'Jangle::Asset',
    :inverse_of => :site,
    :dependent => :destroy

  # -- Validations ----------------------------------------------------------
  validates :label,
    :presence   => true,
    :uniqueness => true
  validates :hostname,
    :presence   => true,
    :uniqueness => true,
    :format     => { :with => /^[\w\.\-]+$/ }
end

app/models/jangle/widget.rb
class Jangle::Widget
  include Jangle::Mongoid::Document
  include Mongoid::Tree

  include Models::Jangle::Extensions::Parse
  include Models::Jangle::Extensions::Render

  # -- Fields ---------------------------------------------------------------
  field :label,    :type => String
  field :slug,     :type => String
  field :content,  :type => String
  field :position, :type => Integer, :default => 0

  # -- Relationships --------------------------------------------------------
  referenced_in :site,
    :class_name => 'Jangle::Site',
    :inverse_of => :widgets
  referenced_in :layout,
    :class_name => 'Jangle::Layout',
    :inverse_of => :widgets
  embeds_many :blocks,
    :class_name => 'Jangle::Block',
    :as         => :container
  accepts_nested_attributes_for :blocks

  # -- Validations ----------------------------------------------------------
  validates :site_id, 
    :presence => true
  validates :label,
    :presence => true
  validates :layout,
    :presence => true

  # -- Class Methods --------------------------------------------------------
  # Tree-like structure for pages
  def self.options_for_select(jangle_site, jangle_widget = nil, current_widget = nil, depth = 0, exclude_self = true, spacer = '. . ')
    out = []
    [current_widget || jangle_site.widgets.roots].flatten.each do |widget|
      next if jangle_widget == widget
      out << [ "#{spacer*depth}#{widget.label}", widget.id ]
      widget.children.each do |child|
        out += options_for_select(jangle_site, jangle_widget, child, depth + 1, spacer)
      end
    end
    return out.compact
  end
end

app/controllers/jangle/assets_controller.rb
module Jangle
  class AssetsController < Jangle::BaseController

    respond_to :html, :js

    def create
      @asset = end_of_association_chain.build(:source => params[:file])
      @asset.name = @asset.source.filename
      create! do
        return render :partial => 'file.html.erb', :object => @asset
      end
    end

  protected

    def begin_of_association_chain
      current_site
    end
  end
end

app/controllers/jangle/base_controller.rb
module Jangle
  class BaseController < InheritedResources::Base

    include InheritedResources::DSL
    include Jangle::Routing::SiteDispatcher

    layout 'jangle/application'

    #before_filter :authenticate_admin!

    before_filter :require_site

    actions :all, :except => [:show]

    respond_to :html

  end
end

app/controllers/jangle/layouts_controller.rb
module Jangle
  class LayoutsController < Jangle::BaseController

    create! do |success, failure|
      success.html do
        flash[:notice] = 'Layout created'
        redirect_to :action => :edit, :id => @layout
      end
      failure.html do
        flash.now[:error] = 'Failed to create layout'
        render :action => :new
      end
    end

    update! do |success, failure|
      success.html do
        flash[:notice] = 'Layout updated'
        redirect_to :action => :edit, :id => @layout
      end
      failure.html do
        flash.now[:error] = 'Failed to update layout'
        render :action => :edit
      end
    end

    destroy! do |success, failure|
      success.html do
        flash[:notice] = 'Layout deleted'
        redirect_to :action => :index
      end
    end

  protected

    def begin_of_association_chain
      current_site
    end

  end
end

app/controllers/jangle/pages_controller.rb
module Jangle
  class PagesController < Jangle::BaseController

    before_filter :check_for_layouts, :only => [:new, :edit]

    create! do |success, failure|
      success.html do
        flash[:notice] = 'Page created'
        redirect_to :action => :edit, :id => @page
      end
      failure.html do
        flash.now[:error] = 'Failed to create page'
        render :action => :new
      end
    end

    update! do |success, failure|
      success.html do
        flash[:notice] = 'Page updated'
        redirect_to :action => :edit, :id => @page
      end
      failure.html do
        flash.now[:error] = 'Failed to update page'
        render :action => :edit
      end
    end

    destroy! do |success, failure|
      success.html do
        flash[:notice] = 'Page deleted'
        redirect_to :action => :index
      end
    end

  protected
    def check_for_layouts
      if Jangle::Layout.count == 0
        flash[:error] = 'No Layouts found. Please create one.'
        redirect_to new_jangle_layout_path
      end
    end

    def begin_of_association_chain
      current_site
    end
  end
end

app/controllers/jangle/rendering_controller.rb
module Jangle
  class RenderingController < ActionController::Base

    include Jangle::Routing::SiteDispatcher

    include Jangle::Render

    before_filter :require_site
    before_filter :load_layout, :only => [ :css, :js ]

    def show
      render_jangle_page
    end

    def css
      render :text => @layout.css, :content_type => 'text/css'
    end

    def js
      render :text => @layout.js, :content_type => 'text/javascript'
    end

  protected

    def load_layout
      @layout = current_site.layouts.find_by_slug(params[:slug])
    end

  end
end

app/controllers/jangle/sites_controller.rb
module Jangle
  class SitesController < Jangle::BaseController
    before_filter :require_site, :except => [ :new, :create ]

    create! do |success, failure|
      success.html do
        flash[:notice] = 'Site created'
        redirect_to :action => :edit, :id => @site
      end
      failure.html do
        flash.now[:error] = 'Failed to create site'
        render :action => :new
      end
    end

    update! do |success, failure|
      success.html do
        flash[:notice] = 'Site updated'
        redirect_to :action => :edit, :id => @site
      end
      failure.html do
        flash.now[:error] = 'Failed to update site'
        render :action => :edit
      end
    end

    destroy! do |success, failure|
      success.html do
        flash[:notice] = 'Site deleted'
        redirect_to :action => :index
      end
    end
  end
end

app/controllers/jangle/widgets_controller.rb
module Jangle
  class WidgetsController < Jangle::BaseController

    before_filter :check_for_layouts, :only => [:new, :edit]

    create! do |success, failure|
      success.html do
        flash[:notice] = 'Widget created'
        redirect_to :action => :edit, :id => @widget
      end
      failure.html do
        flash.now[:error] = 'Failed to create widget'
        render :action => :new
      end
    end

    update! do |success, failure|
      success.html do
        flash[:notice] = 'Widget updated'
        redirect_to :action => :edit, :id => @widget
      end
      failure.html do
        flash.now[:error] = 'Failed to update widget'
        render :action => :edit
      end
    end

    destroy! do |success, failure|
      success.html do
        flash[:notice] = 'Widget deleted'
        redirect_to :action => :index
      end
    end

  protected
    def check_for_layouts
      if Jangle::Layout.count == 0
        flash[:error] = 'No Layouts found. Please create one.'
        redirect_to new_jangle_layout_path
      end
    end

    def begin_of_association_chain
      current_site
    end

  end
end

app/helpers/jangle/base_helper.rb
module Jangle::BaseHelper
end

app/views/jangle/pages/_form.html.erb
<% content_for :right_column do %>
  <div id='page_save' class='box'>
    <label>
      <input type='checkbox'/>
      Published
    </label>
    <button></button>
  </div>
  <%= render :partial => 'jangle/assets/index' %>
<% end %>

<%= form.inputs do %>
  <%= form.input :label, :input_html => { :class => (@page.new_record? ? 'slugify' : nil) } %>
  <div class='page_form_extras'>
    <%= form.input :slug, :input_html => { :class => 'slug' }, :hint => "Special slugs are 'index' and '404'" %>
    <%= form.input :layout_id, :collection => Jangle::Layout.options_for_select(current_site), :input_html => { 'data-page-id' => @page.id }, :label => 'Layout', :include_blank => false %>
    <%= form.input :parent_id, :collection => Jangle::Page.options_for_select(current_site, @page).unshift(['---- Select Parent Page ----', nil]), :include_blank => false %>
    <%= form.input :redirect, :as => :boolean %>
    <%= form.input :redirect_url %>
  </div>
  <div id='form_blocks'>
    <%= form.input :content, :as => :code, :class => 'html' %>
  </div>
<% end %>

<%= form.buttons do %>
  <%= form.input :published, :as => :boolean %>
  <%= form.commit_button %>
  <%= form.commit_button 'Preview', :button_html => { :name => 'preview', :id => 'jangle_page_preview' } %>
<% end %>

app/views/jangle/pages/_form_blocks.html.erb
<div id='form_blocks'>
  <%= fields_for :jangle_blocks, :builder => Jangle::FormBuilder do |jangle_blocks| %>
    <% @jangle_page.cms_tags(true).each do |tag| %>
      <%= jangle_blocks.send(tag.class.name.underscore.downcase.idify, [ tag, @jangle_page ]) %>
    <% end %>
  <% end %>
</div>

app/views/jangle/pages/_index_branch.html.erb
<% 
  jangle_page    ||= index_branch 
  has_children  = jangle_page.children.present?
  has_siblings  = jangle_page.siblings.present?
  branch_open   = (session[:jangle_page_tree] || []).member?(jangle_page.id.to_s) || jangle_page.root?
%>

<li id='<%= dom_id(jangle_page) %>'>
  <div class='item'>
    <div class='toggle <%= 'open' if branch_open %>'>
      <%= 
        if has_children && !jangle_page.root?
          link_to content_tag(:span, 'toggle'), toggle_branch_jangle_page_path(jangle_page), :remote => true
        end
      %>
    </div>
    <div class='icon'>
      <% if has_siblings %>
        <div class='dragger'><span>drag</span></div>
      <% end %>
    </div>
    <div class='action_links'>
      <%= link_to 'Add Child Page', new_jangle_page_path(:'jangle_page[parent_id]' => jangle_page.id) %>
      <%= link_to 'Edit', edit_jangle_page_path(jangle_page) %>
      <%= link_to 'Delete', jangle_page_path(jangle_page), :method => :delete, :confirm => 'Are you sure?' %>
    </div>
    <div class='label'>
      <%= link_to jangle_page.label, edit_jangle_page_path(jangle_page) %>
      <div class='sublabel'>
        <%= link_to jangle_page.url, File.join('/', jangle_page.fullpath), :target => '_blank' %>
      </div>
    </div>
  </div>
  <% if has_children && branch_open %>
    <ul>
      <%= render :partial => 'index_branch', :collection => jangle_page.children %>
    </ul>
  <% end %>
</li>

app/views/jangle/pages/edit.html.erb
<h1> Editing Page </h1>

<%= jangle_form_for @page, :url => { :action => :update } do |form| %>
  <%= render :partial => form %>
<% end %>

app/views/jangle/pages/form_blocks.js.erb
$('#form_blocks').replaceWith('<%= escape_javascript(render(:partial => "form_blocks")) %>');
$.CMS.enable_codemirror();

app/views/jangle/pages/index.html.erb
<%= link_to content_tag(:span, 'Create New Page'), new_jangle_page_path, :class => 'big button' %>
<h1>Pages</h1>

<ul class='list sortable'>
  <%= render :partial => 'index_branch', :collection => @pages %>
</ul>

app/views/jangle/pages/new.html.erb
<h1> New Page </h1>

<%= jangle_form_for @page, :url => { :action => :create } do |form| %>
  <%= render :partial => form %>
<% end %>

app/views/jangle/pages/toggle_branch.js.erb
var li = $('li#jangle_page_<%=@jangle_page.id%>');
li.find('.item .toggle').first().toggleClass('open');

<% if session[:jangle_page_tree].member?(@jangle_page.id.to_s) %>
  if(!li.find('ul')[0]) {
    li.append('<ul><%= escape_javascript(render :partial => "index_branch", :collection => @jangle_page.children) %></ul>');
    $.CMS.enable_sortable_list();
  }
<% else %>
  li.find('ul').remove();
<% end %>